StoreApp/StoreApp.Web/Models/Cart.cs
using StoreApp.Data.Concrete;

namespace StoreApp.Web.Models;

public class Cart
{
    public List<CartItem> Items { get; set; } = new List<CartItem>();

    public virtual void AddItem(Product product, int quantity)
    {
        var item = Items.Where(p => p.Product.Id == product.Id).FirstOrDefault();

        if(item == null)
        {
            Items.Add(new CartItem { Product = product, Quantity = quantity});
        }
        else
        {
            item.Quantity += quantity;
        }
    }

    public virtual void RemoveItem(Product product)
    {
        Items.RemoveAll(i => i.Product.Id == product.Id);
    }
    public decimal CalculateTotal()
    {
        return Items.Sum(i=> i.Product.Price * i.Quantity);
    }

    public virtual void Clear()
    {
        Items.Clear();
    }
}

public class CartItem
{
    public int CartItemId { get; set; }
    public Product Product { get; set; } = new();
    public int Quantity { get; set; }
}

StoreApp/StoreApp.Web/Controllers/OrderController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data.Abstract;
using StoreApp.Data.Concrete;
using StoreApp.Web.Models;

namespace StoreApp.Web.Controllers;

public class OrderController:Controller
{
    private Cart cart;
    private IOrderRepository _orderRepository;

    public OrderController(Cart cartService, IOrderRepository orderRepository)
    {
        cart = cartService;
        _orderRepository = orderRepository;
    }

    public IActionResult Checkout()
    {
        return View(new OrderModel() { Cart = cart });
    }

    [HttpPost]
    public IActionResult Checkout(OrderModel model)
    {
        if(cart.Items.Count == 0)
        {
            ModelState.AddModelError("", "Sepetinizde ürün yok.");
        }
        if (ModelState.IsValid)
        {
            var order = new Order
            {
                Name = model.Name,
                Email = model.Email,
                City = model.City,
                Phone = model.Phone,
                AddressLine = model.AddressLine,
                OrderDate = DateTime.Now,
                OrderItems = cart.Items.Select(i => new StoreApp.Data.Concrete.OrderItem
                {
                    ProductId = i.Product.Id,
                    Price = (double)i.Product.Price,
                    Quantity = i.Quantity
                }).ToList()   
            };

            var payment = ProcessPayment();
            if(payment.Status == "success")
            {
                return RedirectToPage("/Completed", new {OrderId = order.Id});                
            }

            _orderRepository.SaveOrder(order);
            cart.Clear();
            return RedirectToPage("/Completed", new {OrderId = order.Id});
        }
        else //model hatasi varsa
        {
            model.Cart = cart;
            return View(model);
        }
    }

    private Payment ProcessPayment()
    {
        Options options = new Options();
        options.ApiKey = "sandbox-pXQG9RPtDhepbwRq7p17emZeemxLmLmB";
        options.SecretKey = "sandbox-jGj7K5MlHyOHXfHQeverXsGOy3L6UP16";
        options.BaseUrl = "https://sandbox-api.iyzipay.com";
                
        CreatePaymentRequest request = new CreatePaymentRequest();
        request.Locale = Locale.TR.ToString();
        request.ConversationId = "123456789";
        request.Price = "1";
        request.PaidPrice = "1.2";
        request.Currency = Currency.TRY.ToString();
        request.Installment = 1;
        request.BasketId = "B67832";
        request.PaymentChannel = PaymentChannel.WEB.ToString();
        request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

        PaymentCard paymentCard = new PaymentCard();
        paymentCard.CardHolderName = "Yusuf Talha ERDOGMUS";
        paymentCard.CardNumber = "5528790000000008";
        paymentCard.ExpireMonth = "12";
        paymentCard.ExpireYear = "2030";
        paymentCard.Cvc = "123";
        paymentCard.RegisterCard = 0;
        request.PaymentCard = paymentCard;

        Buyer buyer = new Buyer();
        buyer.Id = "BY789";
        buyer.Name = "Yusuf Talha";
        buyer.Surname = "ERDOGMUS";
        buyer.GsmNumber = "+905350000000";
        buyer.Email = "email@email.com";
        buyer.IdentityNumber = "74300864791";
        buyer.LastLoginDate = "2015-10-05 12:43:35";
        buyer.RegistrationDate = "2013-04-21 15:12:09";
        buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
        buyer.Ip = "85.34.78.112";
        buyer.City = "Istanbul";
        buyer.Country = "Turkey";
        buyer.ZipCode = "34732";
        request.Buyer = buyer;

        Address shippingAddress = new Address();
        shippingAddress.ContactName = "Yusuf Talha Erdogmus";
        shippingAddress.City = "Istanbul";
        shippingAddress.Country = "Turkey";
        shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
        shippingAddress.ZipCode = "34742";
        request.ShippingAddress = shippingAddress;

        Address billingAddress = new Address();
        billingAddress.ContactName = "Jane Doe";
        billingAddress.City = "Istanbul";
        billingAddress.Country = "Turkey";
        billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
        billingAddress.ZipCode = "34742";
        request.BillingAddress = billingAddress;

        List<BasketItem> basketItems = new List<BasketItem>();
        BasketItem firstBasketItem = new BasketItem();
        firstBasketItem.Id = "BI101";
        firstBasketItem.Name = "Binocular";
        firstBasketItem.Category1 = "Collectibles";
        firstBasketItem.Category2 = "Accessories";
        firstBasketItem.ItemType = BasketItemType.PHYSICAL.ToString();
        firstBasketItem.Price = "0.3";
        basketItems.Add(firstBasketItem);

        BasketItem secondBasketItem = new BasketItem();
        secondBasketItem.Id = "BI102";
        secondBasketItem.Name = "Game code";
        secondBasketItem.Category1 = "Game";
        secondBasketItem.Category2 = "Online Game Items";
        secondBasketItem.ItemType = BasketItemType.VIRTUAL.ToString();
        secondBasketItem.Price = "0.5";
        basketItems.Add(secondBasketItem);

        BasketItem thirdBasketItem = new BasketItem();
        thirdBasketItem.Id = "BI103";
        thirdBasketItem.Name = "Usb";
        thirdBasketItem.Category1 = "Electronics";
        thirdBasketItem.Category2 = "Usb / Cable";
        thirdBasketItem.ItemType = BasketItemType.PHYSICAL.ToString();
        thirdBasketItem.Price = "0.2";
        basketItems.Add(thirdBasketItem);
        request.BasketItems = basketItems;

        Payment payment = Payment.Create(request, options);
        return payment;
    }
}

StoreApp/StoreApp.Web/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreApp.Data.Abstract;
using StoreApp.Web.Models;

namespace StoreApp.Web.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository _repository;
        public CartModel(IStoreRepository repsository, Cart cartService)
        {
            _repository = repsository;
            Cart = cartService;
        }

        public Cart? Cart { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPost(int Id)
        {
            var product = _repository.Products.FirstOrDefault(i => i.Id == Id);

            if(product != null)
            {
                Cart?.AddItem(product, 1);
            }

            return RedirectToPage("/Cart");
        }

        public IActionResult OnPostRemove(int Id)
        {
            Cart?.RemoveItem(Cart.Items.First(p => p.Product.Id == Id).Product);
            return RedirectToPage("/Cart");
        }
    }
}

StoreApp/StoreApp.Web/Pages/Cart.cshtml
@page
@model CartModel

<h2>Alisveris Sepeti</h2>

@if(Model?.Cart?.Items.Count() == 0)
{
    <div class="alert alert-warning">Ürün Eklenmedi</div>
}
else
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Adet</th>
                <th>Urun</th>
                <th>Fiyat</th>
                <th>Toplam</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model?.Cart?.Items ?? Enumerable.Empty<CartItem>())
            {
                <tr>
                    <td>@item.Quantity</td>
                    <td>@item.Product.Name</td>
                    <td>@item.Product.Price</td>
                    <td>
                        @((item.Quantity * item.Product.Price).ToString()) ₺
                    </td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="Id" value="@item.Product.Id">
                            <button type="submit" class="btn btn-sm btn-danger">Sil</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">Toplam:</td>
                    <td>
                        @Model?.Cart?.CalculateTotal() ₺
                    </td>
                </tr>
            </tfoot>
    </table>
}

<div>
    <a class="btn btn-primary" href="/">Alisverise Devam Et</a>
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Siparisi Tamamla</a>
</div>

StoreApp/StoreApp.Web/Pages/Completed.cshtml
@page
<div class="text-center">
    <h2>Teşekkür Ederiz.</h2>
    <p>#@OrderId numarali Siparişiniz olusturuldu.</p>
    <p>Siparişiniz en kısa sürede adresinize gönderilecektir.</p>
    <a href="/" class="btn btn-primary">Ana Sayfa</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}